# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_product_imageurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hazmat',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazmats', to='backend.Product'),
        ),
    ]
