# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20160416_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(default=b'https://placeholdit.imgix.net/~text?txtsize=19&txt=200%C3%97300&w=200&h=300', max_length=1024),
        ),
    ]
