# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-10 14:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20160417_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='searchName',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='imageUrl',
            field=models.CharField(default='https://placeholdit.imgix.net/~text?txtsize=19&txt=200%C3%97300&w=200&h=300', max_length=1024),
        ),
    ]
